//! Tray icon and the lifecycle rules.
//!
//! # These rules are deliberate
//!
//! Each one is enforced in code rather than left to convention:
//!
//! - **Closing the window does not quit.** The window is destroyed; the core
//!   keeps running in the tray. Not minimise-to-taskbar — actually destroyed,
//!   so its memory is returned.
//! - **Fully exiting is deliberate**: "Quit Lanes" in the tray's Settings
//!   submenu, or turning "Close to tray" off so that X quits.
//! - **The tray menu contains no bare "Exit".** Quit lives inside the Settings
//!   submenu so it cannot be hit by accident.
//! - **Left-click opens the compact flyout. Double-click opens the full
//!   window.**
//!
//! # Threading
//!
//! The tray needs a Windows message pump, and a message pump owns its thread.
//! The core owns COM and all audio state on a different thread. They talk over
//! channels — the same arrangement, and for the same reason, as the API server.

use std::sync::mpsc::Sender;
use std::sync::Mutex;

use tray_icon::menu::{CheckMenuItem, Menu, MenuEvent, MenuItem, PredefinedMenuItem, Submenu};
use tray_icon::{Icon, MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};

/// What the tray asks the core to do.
#[derive(Debug, Clone)]
pub enum TrayCommand {
    ShowWindow,
    /// Open the quick mixer. From the menu's "Quick mixer" item.
    ShowFlyout,
    /// Open the quick mixer, or close it if it is open. From a click on the
    /// icon, which is how every notification-area flyout in Windows behaves.
    ///
    /// Separate from [`TrayCommand::ShowFlyout`] because the two must differ:
    /// opening the menu takes focus, which closes an open flyout, so a toggle
    /// from the menu would see "just closed" and refuse to open it again.
    ToggleFlyout,
    ToggleMuteAll,
    SetStartWithWindows(bool),
    SetStartMinimised(bool),
    SetCloseToTray(bool),
    /// Confirmed by the user first - see `confirm_restore`.
    RestoreWindowsSettings,
    /// Stop being paused after a Restore, and manage applications again.
    Resume,
    /// Switch to the saved profile with this name.
    ActivateProfile(String),
    /// Open the mixer, or close it if it is open. From a hotkey.
    ToggleWindow,
    /// Open the settings window.
    ShowSettings,
    /// A registered hotkey was pressed. Carries its normalised keys.
    Hotkey(String),
    /// Which of the hotkeys Windows accepted, sent after every registration.
    HotkeysRegistered(Vec<(String, crate::hotkeys::Registration)>),
    /// The only programmatic path to a full exit.
    Quit,
}

/// The parts of the tray menu that follow the mixer.
///
/// # Why this is handed over rather than set directly
///
/// The menu belongs to the thread running the message loop - the menu types
/// are not thread-safe, and Windows menus belong to the thread that made them.
/// The mixer's state belongs to the core thread. So the core leaves the latest
/// view here and wakes the loop, which applies it on its own thread.
///
/// Only the newest view matters: if two arrive before the loop wakes, the older
/// one is simply replaced. A queue would replay states nobody will see.
///
/// Before this existed the "Mute all" tick was set once, at startup, and was
/// wrong from the first time anything other than the tray muted Master.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TrayView {
    /// Master's mute, which is what "Mute all" means.
    pub muted: bool,
    /// Every saved profile, in order.
    pub profiles: Vec<String>,
    /// The profile the mixer currently matches.
    pub active: Option<String>,
    /// Every hotkey's keys, normalised. The tray thread registers these.
    pub hotkeys: Vec<String>,
    /// Paused after a Restore: the menu offers "Resume Lanes" at the top.
    pub paused: bool,
}

static PENDING: Mutex<Option<TrayView>> = Mutex::new(None);

/// Hand the tray menu a new view. Safe from any thread.
pub fn publish(view: TrayView) {
    if let Ok(mut slot) = PENDING.lock() {
        *slot = Some(view);
    }
    crate::shutdown::wake();
}

fn take_pending() -> Option<TrayView> {
    PENDING.lock().ok().and_then(|mut slot| slot.take())
}

/// The application mark, as raw pixels compiled into the executable.
///
/// # Why raw pixels and not a PNG
///
/// `tray-icon` wants an RGBA buffer. Shipping a PNG would mean carrying an
/// image decoder in a program whose entire job is audio, to decode one 32x32
/// picture, once. The bytes are 4 KB flat — smaller than the decoder — and
/// `include_bytes!` puts them in the binary, so there is nothing beside the
/// executable that can go missing.
///
/// `assets/tray-32.rgba` is generated by `tools/make_icon.ps1` and committed.
/// The script is the source of truth for the mark; this is its output.
///
/// # Why 32 and not 16
///
/// Windows scales the tray icon to whatever the current DPI asks for. Handing
/// it the larger bitmap means it downscales, which is the direction that looks
/// acceptable; at 150% scaling a 16x16 icon is upscaled and visibly soft.
fn app_icon() -> Option<Icon> {
    const SIZE: u32 = 32;
    const PIXELS: &[u8] = include_bytes!("../../assets/tray-32.rgba");

    // A wrong-sized asset is a build mistake, not a run-time condition, but
    // failing quietly here would show an empty tray slot with no explanation.
    debug_assert_eq!(PIXELS.len(), (SIZE * SIZE * 4) as usize);

    Icon::from_rgba(PIXELS.to_vec(), SIZE, SIZE).ok()
}

pub struct TrayHandles {
    _tray: tray_icon::TrayIcon,
    ids: MenuIds,
    /// The top-level menu, kept so "Resume Lanes" can be put in and taken out.
    menu: Menu,
    /// Shown at the top of the menu only while paused - a permanent, greyed-out
    /// item would be clutter the other 99% of the time.
    resume: MenuItem,
    resume_separator: PredefinedMenuItem,
    resume_shown: bool,
    mute_all: CheckMenuItem,
    profiles: Submenu,
    /// The items currently in the Profiles submenu, and which profile each is.
    profile_items: Vec<(tray_icon::menu::MenuId, String, CheckMenuItem)>,
    /// What the Profiles submenu was last built from, so it is rebuilt only
    /// when the list of names changes and not every time a tick moves.
    profile_names: Vec<String>,
    /// The hotkeys registered with Windows, by the id they were registered
    /// under. `None` until the first view, so an empty first list still
    /// registers - and reports - nothing rather than being skipped.
    hotkeys: Option<Vec<(i32, String)>>,
}

struct MenuIds {
    open: tray_icon::menu::MenuId,
    flyout: tray_icon::menu::MenuId,
    mute_all: tray_icon::menu::MenuId,
    start_with_windows: tray_icon::menu::MenuId,
    start_minimised: tray_icon::menu::MenuId,
    close_to_tray: tray_icon::menu::MenuId,
    restore: tray_icon::menu::MenuId,
    resume: tray_icon::menu::MenuId,
    hotkeys: tray_icon::menu::MenuId,
    quit: tray_icon::menu::MenuId,
}

/// Build the tray icon and its menu.
///
/// Must be called on the thread that will run the message pump.
pub fn build(
    muted: bool,
    start_with_windows: bool,
    start_minimised: bool,
    close_to_tray: bool,
) -> Result<TrayHandles, String> {
    let menu = Menu::new();

    let open = MenuItem::new("Open Lanes", true, None);
    let flyout = MenuItem::new("Quick mixer", true, None);
    let mute_all = CheckMenuItem::new("Mute all", true, muted, None);

    // Filled by `apply_view` as soon as the core publishes the first view,
    // which it does before it handles anything else.
    let profiles = Submenu::new("Profiles", true);

    // Settings is a submenu because Quit lives inside it. There is no bare Exit
    // in the tray menu — putting Quit one level down is what stops it being
    // hit by accident.
    let settings = Submenu::new("Settings", true);
    let start_with_windows_item =
        CheckMenuItem::new("Start with Windows", true, start_with_windows, None);
    let start_minimised_item =
        CheckMenuItem::new("Start minimised to tray", true, start_minimised, None);
    let close_to_tray_item = CheckMenuItem::new("Close to tray", true, close_to_tray, None);
    let restore = MenuItem::new("Restore Windows audio settings…", true, None);
    let resume = MenuItem::new("Resume Lanes (paused after a Restore)", true, None);
    let resume_separator = PredefinedMenuItem::separator();
    // The settings window: hotkeys, ignored apps, notifications, backup and
    // diagnostics. The toggles above stay here because they are one click.
    let hotkeys = MenuItem::new("Open settings…", true, None);
    let quit = MenuItem::new("Quit Lanes", true, None);

    settings
        .append_items(&[
            &start_with_windows_item,
            &start_minimised_item,
            &close_to_tray_item,
            &PredefinedMenuItem::separator(),
            &hotkeys,
            &PredefinedMenuItem::separator(),
            &restore,
            &PredefinedMenuItem::separator(),
            &quit,
        ])
        .map_err(|e| e.to_string())?;

    menu.append_items(&[
        &open,
        &flyout,
        &PredefinedMenuItem::separator(),
        &mute_all,
        &profiles,
        &PredefinedMenuItem::separator(),
        &settings,
    ])
    .map_err(|e| e.to_string())?;

    let ids = MenuIds {
        open: open.id().clone(),
        flyout: flyout.id().clone(),
        mute_all: mute_all.id().clone(),
        start_with_windows: start_with_windows_item.id().clone(),
        start_minimised: start_minimised_item.id().clone(),
        close_to_tray: close_to_tray_item.id().clone(),
        restore: restore.id().clone(),
        resume: resume.id().clone(),
        hotkeys: hotkeys.id().clone(),
        quit: quit.id().clone(),
    };

    // Right-click only. The crate opens the menu on a left click too unless
    // told not to, and a left click belongs to the quick mixer. The menu is
    // modal on this thread, so a left click that opened it would also hold the
    // click's own action back until the menu was dismissed.
    let mut builder = TrayIconBuilder::new()
        .with_menu_on_left_click(false)
        .with_menu(Box::new(menu.clone()))
        // A development copy says so: two identical icons in the tray make it
        // far too easy to use the wrong one (see `instance::may_manage`).
        .with_tooltip(if crate::instance::is_separate() {
            "Lanes (test copy)"
        } else {
            "Lanes"
        });

    if let Some(icon) = app_icon() {
        builder = builder.with_icon(icon);
    }

    let tray = builder.build().map_err(|e| e.to_string())?;

    let mut handles = TrayHandles {
        _tray: tray,
        ids,
        menu,
        resume,
        resume_separator,
        resume_shown: false,
        mute_all,
        profiles,
        profile_items: Vec::new(),
        // Deliberately not the empty list, so the first view always builds
        // the submenu - including the "no profiles yet" line.
        profile_names: vec![String::new()],
        hotkeys: None,
    };
    handles.apply_view(&TrayView {
        muted,
        ..TrayView::default()
    });

    Ok(handles)
}

impl TrayHandles {
    /// Register exactly these hotkeys, replacing whatever was registered.
    ///
    /// Returns what Windows said about each, for the core to report. `None`
    /// when the list is unchanged, so nothing is re-registered - and nothing
    /// reported - every time a fader moves.
    fn register_hotkeys(&mut self, wanted: &[String]) -> Option<Vec<(String, crate::hotkeys::Registration)>> {
        use crate::hotkeys::Registration;
        use windows::Win32::UI::Input::KeyboardAndMouse::{
            RegisterHotKey, UnregisterHotKey, HOT_KEY_MODIFIERS, MOD_NOREPEAT,
        };

        let current: Vec<String> = self
            .hotkeys
            .iter()
            .flatten()
            .map(|(_, keys)| keys.clone())
            .collect();
        if self.hotkeys.is_some() && current == wanted {
            return None;
        }

        for (id, _) in self.hotkeys.take().into_iter().flatten() {
            unsafe {
                let _ = UnregisterHotKey(None, id);
            }
        }

        let mut registered = Vec::new();
        let mut results = Vec::new();

        for (index, keys) in wanted.iter().enumerate() {
            let id = index as i32 + 1;

            let result = match crate::hotkeys::parse(keys) {
                Err(why) => Registration::Failed(why),
                Ok((chord, _)) => {
                    // MOD_NOREPEAT: one press, one action. Holding a mute key
                    // down would otherwise toggle it on and off at the
                    // keyboard's repeat rate.
                    let modifiers = HOT_KEY_MODIFIERS(chord.modifiers) | MOD_NOREPEAT;
                    match unsafe { RegisterHotKey(None, id, modifiers, chord.key) } {
                        Ok(()) => {
                            registered.push((id, keys.clone()));
                            Registration::Active
                        }
                        // ERROR_HOTKEY_ALREADY_REGISTERED
                        Err(e) if e.code().0 as u32 == 0x8007_0581 => Registration::InUse,
                        Err(e) => Registration::Failed(e.message().to_string()),
                    }
                }
            };

            results.push((keys.clone(), result));
        }

        self.hotkeys = Some(registered);
        Some(results)
    }

    /// The keys a registered hotkey id stands for.
    fn hotkey_keys(&self, id: i32) -> Option<String> {
        self.hotkeys
            .iter()
            .flatten()
            .find(|(registered, _)| *registered == id)
            .map(|(_, keys)| keys.clone())
    }

    /// Bring the menu into line with the mixer.
    fn apply_view(&mut self, view: &TrayView) {
        self.mute_all.set_checked(view.muted);

        if view.paused != self.resume_shown {
            if view.paused {
                let _ = self.menu.insert(&self.resume, 0);
                let _ = self.menu.insert(&self.resume_separator, 1);
            } else {
                let _ = self.menu.remove(&self.resume);
                let _ = self.menu.remove(&self.resume_separator);
            }
            self.resume_shown = view.paused;
        }

        if view.profiles != self.profile_names {
            while self.profiles.remove_at(0).is_some() {}
            self.profile_items.clear();

            if view.profiles.is_empty() {
                // Said rather than shown as an empty or disabled submenu: an
                // empty menu reads as broken, and this says how to fill it.
                let hint = MenuItem::new("None yet - save one in the mixer", false, None);
                let _ = self.profiles.append(&hint);
            }

            for name in &view.profiles {
                let item = CheckMenuItem::new(name, true, false, None);
                let _ = self.profiles.append(&item);
                self.profile_items
                    .push((item.id().clone(), name.clone(), item));
            }

            self.profile_names = view.profiles.clone();
        }

        self.tick_profile(view.active.as_deref());
    }

    /// Tick exactly one profile, or none.
    ///
    /// Needed on a click as well as on a new view. A check item toggles itself
    /// when clicked, so clicking the profile that is already active would untick
    /// it - and switching to it changes nothing, so no new view arrives to put
    /// the tick back.
    fn tick_profile(&self, active: Option<&str>) {
        for (_, name, item) in &self.profile_items {
            item.set_checked(active.is_some_and(|a| a.eq_ignore_ascii_case(name)));
        }
    }

    /// Translate a menu click into a command.
    pub fn menu_command(&self, event: &MenuEvent, current: &Toggles) -> Option<TrayCommand> {
        let id = &event.id;

        if let Some((_, name, _)) = self.profile_items.iter().find(|(item, _, _)| item == id) {
            // Ticked straight away rather than when the core answers: the menu
            // has already closed, and the core's view corrects it if the switch
            // somehow fails.
            self.tick_profile(Some(name));
            return Some(TrayCommand::ActivateProfile(name.clone()));
        }

        if *id == self.ids.open {
            Some(TrayCommand::ShowWindow)
        } else if *id == self.ids.flyout {
            Some(TrayCommand::ShowFlyout)
        } else if *id == self.ids.mute_all {
            Some(TrayCommand::ToggleMuteAll)
        } else if *id == self.ids.start_with_windows {
            Some(TrayCommand::SetStartWithWindows(
                !current.start_with_windows,
            ))
        } else if *id == self.ids.start_minimised {
            Some(TrayCommand::SetStartMinimised(!current.start_minimised))
        } else if *id == self.ids.close_to_tray {
            Some(TrayCommand::SetCloseToTray(!current.close_to_tray))
        } else if *id == self.ids.hotkeys {
            Some(TrayCommand::ShowSettings)
        } else if *id == self.ids.restore {
            confirm_restore().then_some(TrayCommand::RestoreWindowsSettings)
        } else if *id == self.ids.resume {
            Some(TrayCommand::Resume)
        } else if *id == self.ids.quit {
            Some(TrayCommand::Quit)
        } else {
            None
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct Toggles {
    pub start_with_windows: bool,
    pub start_minimised: bool,
    pub close_to_tray: bool,
}

/// What a click on the icon itself was.
///
/// Deliberately NOT translated straight into a command. Windows delivers the
/// constituent single clicks *as well as* the double click, so acting on a
/// single click the moment it arrives makes every double-click fire both
/// actions: `ShowFlyout` and then `ShowWindow`.
///
/// [`run_message_loop`] holds a single click for the system double-click
/// interval and cancels it if a double-click follows.
enum IconClick {
    Single,
    Double,
}

fn icon_click(event: &TrayIconEvent) -> Option<IconClick> {
    match event {
        TrayIconEvent::Click {
            button: MouseButton::Left,
            button_state: MouseButtonState::Up,
            ..
        } => Some(IconClick::Single),
        TrayIconEvent::DoubleClick {
            button: MouseButton::Left,
            ..
        } => Some(IconClick::Double),
        _ => None,
    }
}

/// Pump Windows messages until told to stop.
///
/// A message pump owns its thread, which is why the core runs on another one.
///
/// # Idle cost
///
/// Waits with an **infinite** timeout whenever nothing is pending, so an idle
/// tray costs nothing — no polling, ~0% CPU, no measurable wakeups. The only time a timeout is used
/// is the few hundred milliseconds after a left-click, while waiting to see
/// whether it becomes a double-click.
pub fn run_message_loop(mut tray: TrayHandles, commands: Sender<TrayCommand>, toggles: Toggles) {
    use windows::Win32::UI::WindowsAndMessaging::{
        DispatchMessageW, MsgWaitForMultipleObjectsEx, PeekMessageW, TranslateMessage, MSG,
        MWMO_INPUTAVAILABLE, PM_REMOVE, QS_ALLINPUT, WM_HOTKEY, WM_QUIT,
    };
    // Lives under Input::KeyboardAndMouse, not WindowsAndMessaging.
    use windows::Win32::UI::Input::KeyboardAndMouse::GetDoubleClickTime;

    let menu_events = MenuEvent::receiver();
    let icon_events = TrayIconEvent::receiver();
    let mut toggles = toggles;

    // The user's own setting, not a hardcoded guess.
    let double_click_window =
        std::time::Duration::from_millis(unsafe { GetDoubleClickTime() } as u64);

    // A left-click that is waiting to find out whether it is really half of a
    // double-click.
    let mut pending_single: Option<std::time::Instant> = None;

    loop {
        // Asked to stop from elsewhere - the API's `quit`, which the
        // uninstaller and `--quit` both use. Checked first so a quit is acted
        // on before any queued click.
        if crate::shutdown::requested() {
            return;
        }

        // --- the core has something new for the menu, or new hotkeys ---
        if let Some(view) = take_pending() {
            tray.apply_view(&view);
            if let Some(results) = tray.register_hotkeys(&view.hotkeys) {
                let _ = commands.send(TrayCommand::HotkeysRegistered(results));
            }
        }

        // --- menu events ---
        while let Ok(event) = menu_events.try_recv() {
            if let Some(command) = tray.menu_command(&event, &toggles) {
                // Keep our copy of the toggles in step, so the next click
                // computes the right inversion.
                match &command {
                    TrayCommand::SetStartWithWindows(v) => toggles.start_with_windows = *v,
                    TrayCommand::SetStartMinimised(v) => toggles.start_minimised = *v,
                    TrayCommand::SetCloseToTray(v) => toggles.close_to_tray = *v,
                    _ => {}
                }

                let quitting = matches!(command, TrayCommand::Quit);
                let _ = commands.send(command);

                if quitting {
                    return;
                }
            }
        }

        // --- icon clicks ---
        while let Ok(event) = icon_events.try_recv() {
            match icon_click(&event) {
                Some(IconClick::Single) => pending_single = Some(std::time::Instant::now()),
                Some(IconClick::Double) => {
                    // Cancel the single click this double-click also produced.
                    pending_single = None;
                    let _ = commands.send(TrayCommand::ShowWindow);
                }
                None => {}
            }
        }

        // --- has a held single click outlived the double-click window? ---
        if let Some(since) = pending_single {
            if since.elapsed() >= double_click_window {
                pending_single = None;
                let _ = commands.send(TrayCommand::ToggleFlyout);
            }
        }

        // Sleep until something happens, or until the held click matures.
        let timeout = match pending_single {
            Some(since) => double_click_window
                .saturating_sub(since.elapsed())
                .as_millis()
                .max(1) as u32,
            None => u32::MAX, // INFINITE
        };

        unsafe {
            MsgWaitForMultipleObjectsEx(None, timeout, QS_ALLINPUT, MWMO_INPUTAVAILABLE);

            let mut message = MSG::default();
            while PeekMessageW(&mut message, None, 0, 0, PM_REMOVE).as_bool() {
                if message.message == WM_QUIT {
                    return;
                }
                // Posted to this thread, not to a window, because the hotkeys
                // were registered without one. Nothing to dispatch it to.
                if message.message == WM_HOTKEY {
                    if let Some(keys) = tray.hotkey_keys(message.wParam.0 as i32) {
                        let _ = commands.send(TrayCommand::Hotkey(keys));
                    }
                    continue;
                }
                let _ = TranslateMessage(&message);
                DispatchMessageW(&message);
            }
        }
    }
}

/// Ask before putting Windows audio back as it was before Lanes.
///
/// Restore undoes everything Lanes has done to every application at once, and
/// a tray menu item is easy to hit by mistake, so it asks. A plain Windows
/// message box, on the tray's own thread, which owns the menu that was clicked.
fn confirm_restore() -> bool {
    use windows::core::w;
    use windows::Win32::UI::WindowsAndMessaging::{
        MessageBoxW, IDYES, MB_DEFBUTTON2, MB_ICONWARNING, MB_YESNO,
    };

    let answer = unsafe {
        MessageBoxW(
            None,
            w!("Put Windows audio back as it was before Lanes?\n\n\
Every app goes back to 100%, unmuted, on the default device, and Windows' \
default device and volume go back to how they were. Apps that are not running \
are reset the next time they play.\n\n\
Lanes then pauses until you resume it from this menu. Your channels, rules \
and profiles are kept."),
            w!("Lanes"),
            MB_YESNO | MB_ICONWARNING | MB_DEFBUTTON2,
        )
    };
    answer == IDYES
}
