//! Embed the application icon and version information in the executable.
//!
//! Windows takes an executable's icon from a resource inside the file, not from
//! anything beside it, so this is the only way a double-clicked
//! `Lanes.exe` shows the mark rather than a blank page. The same
//! resource is what Explorer, the taskbar, Alt+Tab and an installer's shortcut
//! all read.
//!
//! `assets/icon.ico` is generated by `tools/make_icon.ps1` and committed, so a
//! normal build never needs the script to have been run.

fn main() {
    // Only Windows has this concept, and the crate is a no-op elsewhere — but
    // being explicit means a future non-Windows build fails on the audio code,
    // which is the honest place, rather than here.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    println!("cargo:rerun-if-changed=../assets/icon.ico");

    let mut resource = winresource::WindowsResource::new();
    resource.set_icon("../assets/icon.ico");
    resource.set("ProductName", "Lanes");
    resource.set("FileDescription", "Per-application audio channels for Windows");
    resource.set("LegalCopyright", "Copyright (C) 2026 MAYBE-33. Licensed under the GPL, version 3 or later.");

    // A failure here costs an icon, not a working program. Saying so and
    // carrying on beats failing a build over decoration — but it is said,
    // because a silently iconless build is confusing to inherit.
    if let Err(e) = resource.compile() {
        println!("cargo:warning=could not embed the icon: {e}");
    }
}
